"""Adding constraint unique to name column from Category

Revision ID: 009ba71c6df8
Revises: bf849a4c4b7a
Create Date: 2026-06-13 09:47:25.008582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '009ba71c6df8'
down_revision = 'bf849a4c4b7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
