"""Renaming column category from Transactios to category_id to avoid FKs refs errors

Revision ID: 09a5d519016d
Revises: f3b590e20915
Create Date: 2026-06-10 10:24:01.590099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09a5d519016d'
down_revision = 'f3b590e20915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.String(length=32), nullable=False))
        batch_op.drop_constraint(batch_op.f('transactions_category_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('transactions_category_fkey'), 'categories', ['category'], ['id'])
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
