"""Adding composed constraint unique to name and planning_id column from Category, asserting than a category can't be created multiple times with equals names in the same table

Revision ID: 12a169518e75
Revises: 85a1955be07d
Create Date: 2026-06-13 10:00:59.531142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12a169518e75'
down_revision = '85a1955be07d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_category_name_planning', ['name', 'planning_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('uq_category_name_planning', type_='unique')

    # ### end Alembic commands ###
