"""Adding updated_by and created_by columns to table planning certify auditability and implemented the planning service.

Revision ID: 1abcc20a9028
Revises: 222f675a9320
Create Date: 2026-06-16 16:01:44.680175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1abcc20a9028'
down_revision = '222f675a9320'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plannings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['updated_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plannings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('updated_by')
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
