"""removing unique from column name from Category

Revision ID: 85a1955be07d
Revises: 009ba71c6df8
Create Date: 2026-06-13 09:53:53.610215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a1955be07d'
down_revision = '009ba71c6df8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('categories_name_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('categories_name_key'), ['name'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
