"""Linking categories with planning adding fk planning_id

Revision ID: bf849a4c4b7a
Revises: 09a5d519016d
Create Date: 2026-06-13 01:48:41.433695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf849a4c4b7a'
down_revision = '09a5d519016d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planning_id', sa.String(length=32), nullable=True))
        batch_op.create_foreign_key(None, 'plannings', ['planning_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('planning_id')

    # ### end Alembic commands ###
